package pt.example.dao;

import java.util.List;

import javax.persistence.Query;

import pt.example.entity.RC_MOV_RECLAMACAO;

public class RC_MOV_RECLAMACAODao extends GenericDaoJpaImpl<RC_MOV_RECLAMACAO, Integer>
		implements GenericDao<RC_MOV_RECLAMACAO, Integer> {
	public RC_MOV_RECLAMACAODao() {
		super(RC_MOV_RECLAMACAO.class);
	}

	public List<RC_MOV_RECLAMACAO> getbyid(Integer id) {

		Query query = entityManager.createQuery("Select a from RC_MOV_RECLAMACAO a where a.ID_RECLAMACAO = :id ");
		query.setParameter("id", id);
		List<RC_MOV_RECLAMACAO> data = query.getResultList();
		return data;

	}

	public List<RC_MOV_RECLAMACAO> getbyAccoesabertas(Integer id, String tipo) {

		Query query = entityManager
				.createNativeQuery("select count(*) as total, '' as cps from  RC_MOV_RECLAMACAO_PLANOS_ACCOES  a "
						+ "inner join GT_MOV_TAREFAS b on a.ID_TAREFA =   b.ID_TAREFA " + "where ID_RECLAMACAO  = " + id
						+ " and a.TIPO = '" + tipo + "' and b.ESTADO in ('P','L','E')");

		List<RC_MOV_RECLAMACAO> data = query.getResultList();
		return data;

	}

	public List<RC_MOV_RECLAMACAO> getall() {

		Query query = entityManager.createQuery(
				"Select a from RC_MOV_RECLAMACAO a where a.INATIVO != 1 order by a.DATA_RECLAMACAO desc, a.ID_RECLAMACAO desc  ");
		List<RC_MOV_RECLAMACAO> data = query.getResultList();
		return data;

	}

	public List<RC_MOV_RECLAMACAO> getall2() {

		Query query = entityManager.createQuery(
				"Select a.ID_RECLAMACAO,a.TITULO,a.NUMERO_RECLAMACAO_CLIENTE,a.DATA_RECLAMACAO,a.REJEICAO,a.ID_TIPO_RECLAMACAO,a.UTZ_RESPONSAVEL,a.GRAU_IMPORTANCIA,a.ID_CLIENTE,a.NOME_CLIENTE,a.MORADA_CLIENTE,a.ETSNUM,a.CONTATO_CLIENTE,a.EMAIL_CLIENTE,a.TELEFONE_CLIENTE,a.REFERENCIA,a.DESIGNACAO_REF,a.FAMILIA_REF,a.LOTE,a.TIPO_DEFEITO,a.RECLAMACAO_REVISTA,a.QTD_ENVIADA,a.QTD_RECUSADA,a.DEVOLUCAO,a.OBSERVACOES_RECLAMACAO,a.STEP1CONCLUIDO,a.STEP2CONCLUIDO,a.STEP3CONCLUIDO,a.STEP4CONCLUIDO,a.STEP5CONCLUIDO,a.STEP6CONCLUIDO,a.STEP7CONCLUIDO,a.STEP8CONCLUIDO,a.DESCRICAO_PROBLEMA,a.DESCRICAO_PROBLEMA_IDIOMA_CLIENTE,a.PROBLEMA_REPETIDO,a.NUMERO_RECLAMACAO_REPETIDA,a.RECLAMACAO_REPETIDA_ACEITE,a.ACCOES_EVITAR,a.OBSERVACOES_ACCOES_EVITAR,a.CAUSAS_PROBLEMA,a.CAUSAS_PROBLEMA_IDIOMA_CLIENTE,a.REF_IGUAIS,a.RECLAMACAO_ENCERRADA,a.DATA_FECHO,a.OBSERVACOES_RESULTADOS,a.TIPO_CAMPO_LOTE,a.CUSTOS_EXTERNA,a.CUSTOS_INTERNA,a.CUSTOS_DEVOLUCAO,a.CUSTOS_OUTROS,a.CUSTOS_TOTAL,a.CUSTOS_INTERNA_QTD_CLASSIF,a.CUSTOS_INTERNA_QTD_REJEITADA,a.CUSTOS_REJEICAO_INTERNA,a.CUSTOS_EXTERNA_QTD_CLASSIF,a.CUSTOS_EXTERNA_QTD_REJEITADA,a.CUSTOS_REJEICAO_EXTERNA,a.TIPO_RECLAMACAO,a.DATA_CRIA,a.UTZ_CRIA,a.DATA_ULT_MODIF,a.UTZ_ULT_MODIF,a.DATA_ANULACAO,a.UTZ_ANULACAO,a.INATIVO,a.STEP1CONCLUIDO_UTZ,a.STEP1CONCLUIDO_DATA,a.STEP2CONCLUIDO_UTZ,a.STEP2CONCLUIDO_DATA,a.STEP3CONCLUIDO_UTZ,a.STEP3CONCLUIDO_DATA,a.STEP4CONCLUIDO_UTZ,a.STEP4CONCLUIDO_DATA,a.STEP5CONCLUIDO_UTZ,a.STEP5CONCLUIDO_DATA,a.STEP6CONCLUIDO_UTZ,a.STEP6CONCLUIDO_DATA,a.STEP7CONCLUIDO_UTZ,a.STEP7CONCLUIDO_DATA,a.STEP8CONCLUIDO_UTZ,a.STEP8CONCLUIDO_DATA,a.STEP1CONCLUIDO_DATA_MOD,a.STEP2CONCLUIDO_DATA_MOD,a.STEP3CONCLUIDO_DATA_MOD,a.STEP4CONCLUIDO_DATA_MOD,a.STEP5CONCLUIDO_DATA_MOD,a.STEP6CONCLUIDO_DATA_MOD,a.STEP7CONCLUIDO_DATA_MOD,a.STEP8CONCLUIDO_DATA_MOD,a.DATA_RECLAMACAO_REVISTA,a.DATA_PRAZO_REVISAO,a.RECLAMACAO_COM_REVISAO,a.NUMERO_ENVIOS_GARANTIDOS,a.ENVIO_GARANTIDO_POR,a.DIAS_ATRASO1,a.RESPONSABILIDADE_ATRASO1,a.RESPONSABILIDADE_ATRASO1_DESCRICAO,a.DIAS_ATRASO2,a.RESPONSABILIDADE_ATRASO2,a.RESPONSABILIDADE_ATRASO2_DESCRICAO,a.DIAS_ATRASO3,a.RESPONSABILIDADE_ATRASO3,a.RESPONSABILIDADE_ATRASO3_DESCRICAO,a.DIAS_ATRASO4,a.RESPONSABILIDADE_ATRASO4,a.RESPONSABILIDADE_ATRASO4_DESCRICAO,a.DIAS_ATRASO5,a.RESPONSABILIDADE_ATRASO5,a.RESPONSABILIDADE_ATRASO5_DESCRICAO,a.DIAS_ATRASO6,a.RESPONSABILIDADE_ATRASO6,a.RESPONSABILIDADE_ATRASO6_DESCRICAO,a.DIAS_ATRASO7,a.RESPONSABILIDADE_ATRASO7,a.RESPONSABILIDADE_ATRASO7_DESCRICAO,a.DIAS_ATRASO8,a.RESPONSABILIDADE_ATRASO8,a.RESPONSABILIDADE_ATRASO8_DESCRICAO,a.ESTADO,a.DATA_CANCELADA,a.UTZ_CANCELADA,a.UTZ_FECHO,a.TIPO_OCORRENCIA,a.TIPO_NAO_DETECAO,a.STEP1_DATA,a.STEP2_DATA,a.STEP3_DATA,a.STEP4_DATA,a.STEP5_DATA,a.STEP6_DATA,a.STEP7_DATA,a.STEP8_DATA from RC_MOV_RECLAMACAO a where a.INATIVO != 1 order by a.DATA_RECLAMACAO desc, a.ID_RECLAMACAO desc  ");
		List<RC_MOV_RECLAMACAO> data = query.getResultList();
		return data;

	}

	public List<RC_MOV_RECLAMACAO> getbyidtotaltarefas(Integer id) {

		Query query = entityManager.createNativeQuery(
				"select count(*) from RC_MOV_RECLAMACAO_PLANOS_ACCOES where ID_RECLAMACAO = :id and ESTADO not in ('A','C','R','N') ");
		query.setParameter("id", id);
		List<RC_MOV_RECLAMACAO> data = query.getResultList();
		return data;

	}

}
