-- =============================================================================
-- Conversão de campos DATE para DATETIME em módulos AT_ e QUA_
-- Captura hora além de data em: DATA_CRIA, DATA_MODIF, DATA_ANULA
--
-- Módulos: AT_ (Acidentes de Trabalho) e QUA_ (Qualidade)
-- Data: 2026-09-02
-- =============================================================================

-- ====== AT_ (Acidentes de Trabalho) ======
IF COL_LENGTH('AT_ASSINATURAS_SIMILARES', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE AT_ASSINATURAS_SIMILARES ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('AT_ASSINATURAS_SIMILARES', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE AT_ASSINATURAS_SIMILARES ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('AT_ASSINATURAS_SIMILARES', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE AT_ASSINATURAS_SIMILARES ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('AT_INCIDENTES', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE AT_INCIDENTES ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES', 'DATA_ANULA') IS NOT NULL OR COL_LENGTH('AT_INCIDENTES', 'DATA_ANULACAO') IS NOT NULL
  ALTER TABLE AT_INCIDENTES ALTER COLUMN DATA_ANULACAO DATETIME NULL;

IF COL_LENGTH('AT_INCIDENTES_ACOES', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ACOES ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_ACOES', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ACOES ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_ACOES', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ACOES ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('AT_INCIDENTES_ANEXOS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ANEXOS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_ANEXOS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ANEXOS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_ANEXOS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ANEXOS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('AT_INCIDENTES_ASSINATURAS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ASSINATURAS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_ASSINATURAS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ASSINATURAS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_ASSINATURAS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_ASSINATURAS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('AT_INCIDENTES_CAUSAS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_CAUSAS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_CAUSAS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_CAUSAS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_CAUSAS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_CAUSAS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('AT_INCIDENTES_PESSOAS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_PESSOAS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_PESSOAS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_PESSOAS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('AT_INCIDENTES_PESSOAS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE AT_INCIDENTES_PESSOAS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('AT_OCORRENCIAS_ANEXOS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE AT_OCORRENCIAS_ANEXOS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('AT_OCORRENCIAS_ANEXOS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE AT_OCORRENCIAS_ANEXOS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('AT_OCORRENCIAS_ANEXOS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE AT_OCORRENCIAS_ANEXOS ALTER COLUMN DATA_ANULA DATETIME NULL;

-- ====== QUA_ - EPI ======
IF COL_LENGTH('QUA_EPI_DIC_EPI', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_DIC_EPI ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_DIC_EPI', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_DIC_EPI ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_DIC_EPI', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_DIC_EPI ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_DIC_FAMILIA', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_DIC_FAMILIA ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_DIC_FAMILIA', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_DIC_FAMILIA ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_DIC_FAMILIA', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_DIC_FAMILIA ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_FUNC', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_FUNC ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_FUNC', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_FUNC ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_FUNC', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_FUNC ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_LOCAL', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_LOCAL ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_LOCAL', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_LOCAL ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_LOCAL', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_LOCAL ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_LOCAL_RESP', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_LOCAL_RESP ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_LOCAL_RESP', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_LOCAL_RESP ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_LOCAL_RESP', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_LOCAL_RESP ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_MOV_ENTREGA', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_ENTREGA ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_ENTREGA', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_ENTREGA ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_ENTREGA', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_ENTREGA ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_MOV_ENTREGA_ETIQ', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_ENTREGA_ETIQ ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_ENTREGA_ETIQ', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_ENTREGA_ETIQ ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_ENTREGA_ETIQ', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_ENTREGA_ETIQ ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_MOV_PEDIDO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_PEDIDO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_PEDIDO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_MOV_PEDIDO_HIST', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO_HIST ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_PEDIDO_HIST', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO_HIST ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_PEDIDO_HIST', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO_HIST ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_EPI_MOV_PEDIDO_LIN', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO_LIN ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_PEDIDO_LIN', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO_LIN ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_EPI_MOV_PEDIDO_LIN', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_EPI_MOV_PEDIDO_LIN ALTER COLUMN DATA_ANULA DATETIME NULL;

-- ====== QUA_ - Meios de Controlo ======
IF COL_LENGTH('QUA_MC_ALERTAS_ENVIADOS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_ALERTAS_ENVIADOS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_ALERTAS_ENVIADOS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_ALERTAS_ENVIADOS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_ALERTAS_ENVIADOS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_ALERTAS_ENVIADOS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DECLARACOES_NC', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DECLARACOES_NC ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DECLARACOES_NC', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DECLARACOES_NC ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DECLARACOES_NC', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DECLARACOES_NC ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DERROGACOES', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DERROGACOES', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DERROGACOES', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES_ACOES ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES_ACOES ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES_ACOES ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DERROGACOES_FICHEIROS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES_FICHEIROS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DERROGACOES_FICHEIROS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES_FICHEIROS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DERROGACOES_FICHEIROS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DERROGACOES_FICHEIROS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_ESTADO_METROLOGICO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_ESTADO_METROLOGICO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_ESTADO_METROLOGICO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_ESTADO_METROLOGICO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_ESTADO_METROLOGICO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_ESTADO_METROLOGICO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_MSA', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_MSA ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_MSA', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_MSA ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_MSA', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_MSA ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_PECAS_CROMADAS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_PECAS_CROMADAS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_PECAS_CROMADAS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_PECAS_CROMADAS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_PECAS_CROMADAS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_PECAS_CROMADAS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_RESP_VALIDACAO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_RESP_VALIDACAO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_RESP_VALIDACAO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_RESP_VALIDACAO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_RESP_VALIDACAO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_RESP_VALIDACAO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_RESULTADO_VALIDACAO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_RESULTADO_VALIDACAO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_RESULTADO_VALIDACAO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_RESULTADO_VALIDACAO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_RESULTADO_VALIDACAO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_RESULTADO_VALIDACAO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_SECCOES', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_SECCOES ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_SECCOES', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_SECCOES ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_SECCOES', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_SECCOES ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_TIPO_ACEITACAO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_ACEITACAO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_TIPO_ACEITACAO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_ACEITACAO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_TIPO_ACEITACAO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_ACEITACAO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_TIPO_CALIBRACAO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_CALIBRACAO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_TIPO_CALIBRACAO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_CALIBRACAO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_TIPO_CALIBRACAO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_CALIBRACAO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_DIC_TIPO_VERIF_GABARIT', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_VERIF_GABARIT ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_TIPO_VERIF_GABARIT', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_VERIF_GABARIT ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_DIC_TIPO_VERIF_GABARIT', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_DIC_TIPO_VERIF_GABARIT ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO_CERTIF', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO_CERTIF ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO_CERTIF', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO_CERTIF ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO_CERTIF', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO_CERTIF ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO_FICHEIROS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO_FICHEIROS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO_FICHEIROS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO_FICHEIROS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_ENTIDADES_CALIBRACAO_FICHEIROS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_ENTIDADES_CALIBRACAO_FICHEIROS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_EQUIPAMENTOS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_EQUIPAMENTOS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_EQUIPAMENTOS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_EQUIPAMENTOS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_EQUIPAMENTOS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_EQUIPAMENTOS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_EQUIPAMENTOS_FICHEIROS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_EQUIPAMENTOS_FICHEIROS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_EQUIPAMENTOS_FICHEIROS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_EQUIPAMENTOS_FICHEIROS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_EQUIPAMENTOS_FICHEIROS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_EQUIPAMENTOS_FICHEIROS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_GABARITOS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_GABARITOS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_GABARITOS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_GABARITOS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_GABARITOS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_GABARITOS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_GABARITOS_FICHEIROS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_GABARITOS_FICHEIROS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_GABARITOS_FICHEIROS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_GABARITOS_FICHEIROS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_GABARITOS_FICHEIROS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_GABARITOS_FICHEIROS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MAQUINAS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MAQUINAS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MAQUINAS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MAQUINAS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MAQUINAS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MAQUINAS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP_DET', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP_DET ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP_DET', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP_DET ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP_DET', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP_DET ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP_FICHEIROS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP_FICHEIROS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP_FICHEIROS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP_FICHEIROS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_CALIB_EQUIP_FICHEIROS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_CALIB_EQUIP_FICHEIROS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MOV_VERIF_GABARITO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_GABARITO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_GABARITO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_GABARITO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_GABARITO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_GABARITO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MOV_VERIF_GABARITO_FICHEIROS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_GABARITO_FICHEIROS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_GABARITO_FICHEIROS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_GABARITO_FICHEIROS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_GABARITO_FICHEIROS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_GABARITO_FICHEIROS ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MOV_VERIF_INT_GABARITO', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_INT_GABARITO ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_INT_GABARITO', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_INT_GABARITO ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_INT_GABARITO', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_INT_GABARITO ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MOV_VERIF_MAQUINA', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_MAQUINA ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_MAQUINA', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_MAQUINA ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_MAQUINA', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_MAQUINA ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_MOV_VERIF_SALA', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_SALA ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_SALA', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_SALA ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_MOV_VERIF_SALA', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_MOV_VERIF_SALA ALTER COLUMN DATA_ANULA DATETIME NULL;

IF COL_LENGTH('QUA_MC_SALAS', 'DATA_CRIA') IS NOT NULL
  ALTER TABLE QUA_MC_SALAS ALTER COLUMN DATA_CRIA DATETIME NULL;
IF COL_LENGTH('QUA_MC_SALAS', 'DATA_MODIF') IS NOT NULL
  ALTER TABLE QUA_MC_SALAS ALTER COLUMN DATA_MODIF DATETIME NULL;
IF COL_LENGTH('QUA_MC_SALAS', 'DATA_ANULA') IS NOT NULL
  ALTER TABLE QUA_MC_SALAS ALTER COLUMN DATA_ANULA DATETIME NULL;

-- ====== Verificação ======
-- SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE (TABLE_NAME LIKE 'AT_%' OR TABLE_NAME LIKE 'QUA_%')
-- AND COLUMN_NAME IN ('DATA_CRIA', 'DATA_MODIF', 'DATA_ANULA')
-- ORDER BY TABLE_NAME, COLUMN_NAME;
