-- MAN_GET_ALL_PIPE : correcao de performance
-- Data: 2026-09-10
-- Motivo: a SP retinha uma conexao do pool ~9s, esgotando o pool do WildFly
--         (IJ000453) no arranque de turno, com o quadro pipe a fazer polling
--         a cada 60s em varios clientes simultaneos.
-- Alteracao: a subquery que resolve o LOCAL do utilizador foi retirada do WHERE
--         para uma variavel. Depende apenas de @ID, mas era reavaliada por linha.
--         Medido: 160.065 -> 21 leituras logicas (~89% do total da SP).
-- Semantica: inalterada. Dentro da subquery o alias 'a' refere-se a
--         GER_UTILIZADORES (faz shadowing do 'a' exterior), logo o valor nunca
--         dependeu da linha exterior.

USE SGIID;
GO



ALTER PROCEDURE [dbo].[MAN_GET_ALL_PIPE]
	@ID int,
	@UNIDADE int,
	@EQUIPA int = NULL,
	@UTILIZADOR_FILTRO int = NULL
AS
BEGIN

	-- Resolve o LOCAL/sector do utilizador UMA vez.
	-- Antes esta subquery vivia dentro do WHERE e, apesar de depender apenas de @ID,
	-- era reavaliada uma vez por linha candidata (~7.600x = ~160.000 leituras logicas).
	DECLARE @LOCAL_UTZ int = (
		SELECT TOP 1 c.LOCAL
		FROM GER_UTILIZADORES a
		LEFT JOIN RH_FUNCIONARIOS b ON (CASE WHEN a.COD_UTZ = '9889' THEN 0 ELSE a.COD_UTZ END) = b.COD_FUNC_ORIGEM
		LEFT JOIN RH_SECTORES c ON b.COD_SECTOR = c.COD_SECTOR
		WHERE a.ID_UTILIZADOR = @ID AND a.INATIVO != 1
	);

WITH CTE_LOCALIZACAO AS (
    SELECT CONCAT('E', ID) AS ID, DESCRICAO, UNIDADE FROM MAN_DIC_EDIFICIOS
    UNION ALL
    SELECT CONCAT('P', a.ID), b.DESCRICAO + '/' + a.DESCRICAO, UNIDADE
    FROM MAN_DIC_PISOS a
    INNER JOIN MAN_DIC_EDIFICIOS b ON a.ID_EDIFICIO = b.ID
    UNION ALL
    SELECT CONCAT('D', a.ID), c.DESCRICAO + '/' + b.DESCRICAO + '/' + a.DESCRICAO, UNIDADE
    FROM MAN_DIC_DIVISOES a
    INNER JOIN MAN_DIC_PISOS b ON a.ID_PISO = b.ID
    INNER JOIN MAN_DIC_EDIFICIOS c ON b.ID_EDIFICIO = c.ID
),
CTE_ACOES AS (
    SELECT x.ID_MANUTENCAO_CAB,
           STRING_AGG(xb.DESCRICAO_PT + ' || ' + CAST(ISNULL(x.TEMPO_ESTIMADO, '00:00') AS VARCHAR(5)) + ' || ' + CAST(ISNULL(x.TEMPO, '00:00') AS VARCHAR(5)) + ' || ' + CAST(ISNULL(x.REALIZADA, 0) AS VARCHAR(1)), ';;') AS acoes
    FROM MAN_MOV_MANUTENCAO_ACCOES x
    INNER JOIN GT_DIC_TAREFAS xb ON x.ID_ACAO = xb.ID
    GROUP BY x.ID_MANUTENCAO_CAB
),
CTE_UTILIZADORES_CURSO AS (
    SELECT xg1.ID_MANUTENCAO_CAB,
           STRING_AGG(xe.NOME_UTILIZADOR + ' (' + FORMAT(xg1.DATA_INICIO, 'yyyy-MM-dd HH:mm') + ')', ' | ') AS descricao
    FROM MAN_MOV_MANUTENCAO_OPERARIOS xg1
    LEFT JOIN GER_UTILIZADORES xe ON xg1.ID_OPERARIO = xe.ID_UTILIZADOR
    WHERE xg1.ESTADO = 'E'
    GROUP BY xg1.ID_MANUTENCAO_CAB
),
CTE_UTILIZADORES_SUSPENSO AS (
    SELECT xg1.ID_MANUTENCAO_CAB,
           STRING_AGG(xe.NOME_UTILIZADOR + ' (' + FORMAT(xb.DATA_INICIO, 'yyyy-MM-dd HH:mm') + ')', ' | ') AS descricao
    FROM MAN_MOV_MANUTENCAO_OPERARIOS xg1
    LEFT JOIN MAN_MOV_MANUTENCAO_PAUSAS xb ON xg1.ID_MANUTENCAO_OPERARIOS = xb.ID_MANUTENCAO_OPERARIO
    LEFT JOIN GER_UTILIZADORES xe ON xg1.ID_OPERARIO = xe.ID_UTILIZADOR
    WHERE xg1.ESTADO = 'R' AND xb.ESTADO = 'R'
    GROUP BY xg1.ID_MANUTENCAO_CAB
),
CTE_NOTAS AS (
    SELECT ID_MANUTENCAO_CAB, COUNT(*) AS total_notas
    FROM MAN_MOV_MANUTENCAO_NOTAS
    GROUP BY ID_MANUTENCAO_CAB
),
CTE_DOCUMENTOS AS (
    SELECT ID_PEDIDO, COUNT(*) AS total_documentos_pedido
    FROM MAN_MOV_PEDIDOS_DOCUMENTOS
    GROUP BY ID_PEDIDO
),
CTE_SUSPENSO_OPERARIO AS (
    SELECT ID_MANUTENCAO_CAB, ID_OPERARIO
    FROM MAN_MOV_MANUTENCAO_OPERARIOS
    WHERE ESTADO = 'R'
),
CTE_TOTAL_EM_TRABALHO AS (
    SELECT COUNT(*) AS TOTAL_EM_TRABALHO
    FROM MAN_MOV_MANUTENCAO_OPERARIOS
    WHERE ID_OPERARIO = @ID AND ESTADO IN ('E', 'P')
),
CTE_DESISTENCIAS AS (
    SELECT ID_MANUTENCAO_CAB, COUNT(*) AS DESISTENCIAS
    FROM MAN_MOV_MANUTENCAO_OPERARIOS
    WHERE ESTADO = 'D'
    GROUP BY ID_MANUTENCAO_CAB
),
CTE_SUSPENSO_MOTIVOS AS (
    SELECT xg1.ID_MANUTENCAO_CAB, COUNT(*) AS total_suspensoes
    FROM MAN_MOV_MANUTENCAO_OPERARIOS xg1
    INNER JOIN MAN_MOV_MANUTENCAO_MOTIVOS xs ON xg1.ID_MANUTENCAO_OPERARIOS = xs.ID_MANUTENCAO_OPERARIOS
    WHERE xs.TIPO_MOTIVO = 'SUSPENDER'
    GROUP BY xg1.ID_MANUTENCAO_CAB
),
CTE_STATUS_MAQUINA AS (
    SELECT ID_PEDIDO, ESTADO
    FROM MAN_MOV_MAQUINAS_PARADAS
    WHERE ESTADO = 'P'
),
cte_campo_x AS (
    SELECT xg.ID_MANUTENCAO_CAB, xg.ID_OPERARIO
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY ID_MANUTENCAO_CAB ORDER BY ID_OPERARIO) AS rn
        FROM MAN_MOV_MANUTENCAO_OPERARIOS
        WHERE ID_OPERARIO = @ID AND ESTADO IN ('E')
    ) xg
    WHERE xg.rn = 1
)

SELECT
    a.ID_MANUTENCAO_CAB, a.NUMERO_PEDIDO, a.RESPONSAVEL_PEDIDO, a.DATA_HORA_PEDIDO, a.LOCALIZACAO, a.EQUIPAMENTO,
    a.COMPONENTE, a.DESCRICAO_PEDIDO, a.OBSERVACOES, a.DATA_INICIO, a.DATA_FIM, a.ESTADO, a.TIPO_MANUTENCAO,
    a.UTZ_CRIA, a.DATA_CRIA, a.UTZ_ULT_MODIF, a.DATA_ULT_MODIF, a.TIPO_LOCALIZACAO,
    b.NOME_UTILIZADOR AS responsavel_desc,
    c.NOME AS equipamento_desc,
    d.REFERENCIA AS componente_ref,
    d.DESC_REFERENCIA AS componente_desc,
    e.DESCRICAO AS localizacao_desc,
    f.ID_RESPONSAVEL,
    ca.acoes,
    so.ID_OPERARIO AS OPERARIO_SUSPENSO,
    tet.TOTAL_EM_TRABALHO,
    cx.ID_OPERARIO campo_x,
    a.TIPO_RESPONSAVEL,
    CASE
        WHEN a.TIPO_RESPONSAVEL = 'U' AND a.UTILIZADOR IS NOT NULL THEN gu.NOME_UTILIZADOR
        WHEN a.TIPO_RESPONSAVEL = 'EX' THEN a.NOME_FORNECEDOR
        ELSE f.NOME_EQUIPA
    END AS equipa_utilizador,
    c.DESCRICAO_MANUTENCAO,
    sm.ESTADO AS STATUS_MAQUINA,
    ISNULL(de.DESISTENCIAS, 0) DESISTENCIAS,
    a.DATA_REALIZACAO,
    uc.descricao AS utilizadores_em_curso,
    us.descricao AS utilizadores_em_supenso,
    a.NOTAS_PLANEAMENTO,
    dn.total_notas,
    ISNULL(doc.total_documentos_pedido, 0) total_documentos_pedido,
    CASE
        WHEN a.TIPO_MANUTENCAO = 'P' THEN (
            SELECT STRING_AGG(gu.EMAIL, ',')
            FROM MAN_DIC_AMBITO_UTILIZADORES mau
            INNER JOIN GER_UTILIZADORES gu ON mau.ID_UTILIZADOR = gu.ID_UTILIZADOR
            WHERE mau.ID_EQUIPA = a.AMBITO_MANUTENCAO
        )
        ELSE (SELECT EMAIL FROM GER_UTILIZADORES WHERE ID_UTILIZADOR = a.RESPONSAVEL_PEDIDO)
    END AS EMAIL_RESPONSAVEL,
    ISNULL(smt.total_suspensoes, 0) total_suspensoes,
    nc.NIVEL,
    a.ORDEM, a.PRAZO,
    CASE
        WHEN a.PRAZO IS NOT NULL THEN
            CASE
                WHEN a.PRAZO < CAST(GETDATE() AS date) THEN '#FF8A80'
                WHEN a.PRAZO BETWEEN CAST(GETDATE() AS date) AND DATEADD(DAY, 7, CAST(GETDATE() AS date)) THEN '#fafacb'
                ELSE NULL
            END
        ELSE NULL
    END AS cor_prazo,
    m.MANUTENCOES
FROM MAN_MOV_MANUTENCAO_CAB a
LEFT JOIN GER_UTILIZADORES b ON a.RESPONSAVEL_PEDIDO = b.ID_UTILIZADOR
LEFT JOIN MAN_MOV_MANUTENCAO_EQUIPAMENTOS c ON a.EQUIPAMENTO = c.ID_MANUTENCAO
LEFT JOIN MAN_MOV_MANUTENCAO_COMPONENTES d ON a.COMPONENTE = d.ID
LEFT JOIN CTE_LOCALIZACAO e ON e.ID = CONCAT(ISNULL(a.TIPO_LOCALIZACAO, 'E'), a.LOCALIZACAO)
LEFT JOIN MAN_DIC_EQUIPAS f ON a.TIPO_RESPONSAVEL = 'E' AND a.UTILIZADOR = f.ID
LEFT JOIN CTE_ACOES ca ON ca.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
LEFT JOIN CTE_SUSPENSO_OPERARIO so ON so.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
LEFT JOIN CTE_TOTAL_EM_TRABALHO tet ON 1 = 1
LEFT JOIN cte_campo_x cx ON cx.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
LEFT JOIN GER_UTILIZADORES gu ON gu.ID_UTILIZADOR = a.UTILIZADOR
LEFT JOIN MAN_DIC_NIVEIS_CRITICIDADE nc ON c.NIVEL_CRITICIDADE = nc.ID
LEFT JOIN CTE_STATUS_MAQUINA sm ON sm.ID_PEDIDO = a.ID_MANUTENCAO_CAB
LEFT JOIN CTE_DESISTENCIAS de ON de.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
LEFT JOIN CTE_UTILIZADORES_CURSO uc ON uc.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
LEFT JOIN CTE_UTILIZADORES_SUSPENSO us ON us.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
LEFT JOIN CTE_NOTAS dn ON dn.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
LEFT JOIN CTE_DOCUMENTOS doc ON doc.ID_PEDIDO = a.ID_MANUTENCAO_CAB
LEFT JOIN CTE_SUSPENSO_MOTIVOS smt ON smt.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
LEFT JOIN (
    SELECT ID_ORIGEM, STRING_AGG(a.ID_MANUTENCAO_CAB, ',') MANUTENCOES
    FROM MAN_MOV_MANUTENCAO_CAB a
    WHERE a.ESTADO IN ('P','PE','EM','C','CA','A','RE','V','R','S','E','RP') AND ID_ORIGEM IS NOT NULL
    GROUP BY ID_ORIGEM
) m ON m.ID_ORIGEM = a.ID_MANUTENCAO_CAB
WHERE
    a.ESTADO NOT IN ('C', 'A', 'PE', 'EM')
    AND (
        -- filtro por utilizador
        @UTILIZADOR_FILTRO IS NOT NULL AND (
            (CASE
                WHEN a.TIPO_RESPONSAVEL = 'E' THEN f.ID_RESPONSAVEL
                WHEN a.TIPO_RESPONSAVEL = 'U' AND a.UTILIZADOR IS NOT NULL THEN a.UTILIZADOR
            END) = @UTILIZADOR_FILTRO
            OR EXISTS (SELECT 1 FROM MAN_MOV_MANUTENCAO_OPERARIOS xg
                       WHERE xg.ID_OPERARIO = @UTILIZADOR_FILTRO
                         AND xg.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
                         AND xg.ESTADO IN ('E'))
            OR EXISTS (SELECT 1 FROM MAN_DIC_AMBITO_UTILIZADORES x
                       WHERE x.ID_UTILIZADOR = @UTILIZADOR_FILTRO
                         AND x.ID_EQUIPA = a.AMBITO_MANUTENCAO)
        )
        -- filtro por equipa
        OR @EQUIPA IS NOT NULL AND (
            f.ID = @EQUIPA
            OR (a.TIPO_RESPONSAVEL = 'U' AND EXISTS (
                SELECT 1 FROM MAN_DIC_EQUIPAS_UTILIZADORES eu
                WHERE eu.ID_EQUIPA = @EQUIPA AND eu.ID_UTILIZADOR = a.UTILIZADOR
            ))
            OR EXISTS (
                SELECT 1 FROM MAN_MOV_MANUTENCAO_OPERARIOS xg
                INNER JOIN MAN_DIC_EQUIPAS_UTILIZADORES eu ON xg.ID_OPERARIO = eu.ID_UTILIZADOR
                WHERE eu.ID_EQUIPA = @EQUIPA
                  AND xg.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB
                  AND xg.ESTADO IN ('E')
            )
        )
        -- comportamento existente (sem filtro)
        OR @UTILIZADOR_FILTRO IS NULL AND @EQUIPA IS NULL AND (
            (CASE
                WHEN a.TIPO_RESPONSAVEL = 'E' THEN f.ID_RESPONSAVEL
                WHEN a.TIPO_RESPONSAVEL = 'U' AND a.UTILIZADOR IS NOT NULL THEN a.UTILIZADOR
            END) = @ID
            OR EXISTS (SELECT 1 FROM MAN_MOV_MANUTENCAO_OPERARIOS xg WHERE xg.ID_OPERARIO = @ID AND xg.ID_MANUTENCAO_CAB = a.ID_MANUTENCAO_CAB AND xg.ESTADO IN ('E'))
            OR EXISTS (SELECT 1 FROM MAN_DIC_AMBITO_UTILIZADORES x WHERE x.ID_UTILIZADOR = @ID AND x.ID_EQUIPA = a.AMBITO_MANUTENCAO)
            OR EXISTS (SELECT 1 FROM MAN_DIC_EQUIPAS gd WHERE gd.ID_RESPONSAVEL = @ID AND a.UTILIZADOR = @ID)
            OR EXISTS (SELECT 1 FROM MAN_DIC_EQUIPAS_UTILIZADORES g WHERE g.ID_EQUIPA = f.ID AND g.ID_UTILIZADOR = @ID AND a.ESTADO IN ('P','R'))
            OR EXISTS (SELECT 1 FROM GER_UTILIZADORES xy WHERE xy.ID_UTILIZADOR = @ID AND xy.ADMIN = 1)
        )
    )
    AND (
        @UNIDADE IS NULL OR a.AMBITO_MANUTENCAO = @UNIDADE
        OR (@UTILIZADOR_FILTRO IS NULL AND @EQUIPA IS NULL AND e.UNIDADE = @LOCAL_UTZ AND a.UTILIZADOR IS NULL)
    )
ORDER BY
    CASE WHEN a.ESTADO = 'RE' THEN 0 ELSE 1 END,
    CASE
        WHEN sm.ESTADO = 'P' THEN 0
        WHEN SEGURANCA_AMBIENTE = 1 THEN 1
        ELSE 2
    END,
    ISNULL(a.ORDEM, ISNULL(CASE WHEN sm.ESTADO = 'P' THEN ISNULL(nc.NIVEL, 0) - 1 ELSE nc.NIVEL END, ISNULL(a.ORDEM, 100))),
    ISNULL(a.ORDEM, 0),
    a.ID_MANUTENCAO_CAB;

END
GO
