USE [SGIID]
GO
/****** Object:  StoredProcedure [dbo].[PIN_UPDATE_PIN_DIC_PRODUTOS_PERC_DILUICAO] ******/
/****** ⚠️ ATENÇÃO: se já executou PIN_MELHORIAS_FASE2_2026-07-03.sql NÃO execute ******/
/****** este ficheiro — a versão da SP nesse script já inclui estas correções     ******/
/****** mais os campos novos (HUMIDADE_MIN/MAX, FILTRO_ROBOT). Executar este      ******/
/****** depois da Fase 2 REVERTIA esses campos na SP.                             ******/
/******
 Correções 2026-07-03 (perda de dados ao gerar nova versão de receita):
 1. INSERT do cabeçalho passou a copiar CICLO_PRIMARIO, CICLO_BASE e CICLO_VERNIZ
    (era a causa dos tempos de ciclo desaparecerem na nova versão).
 2. Adicionado INSERT em PIN_MOV_UV_RADIATION — a nova versão não copiava a
    tabela de UV radiation, ficando "Nenhum registo foi encontrado" e sem edição.
 3. Cursor: adicionado "a.VERSAO = c.VERSAO" no join às linhas — sem isto, linhas
    de versões antigas podiam despoletar novas versões de receitas cuja versão
    ativa já não usa o produto.
 4. Bloco "ATUALIZA CONSUMOS" movido para dentro do ciclo — corria apenas depois
    do ciclo, ou seja, só atualizava a ÚLTIMA receita processada.
 (A SP PIN_UPDATE_PIN_DIC_PRE_SET já copia ciclos e UV — não precisa de alteração.)
******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[PIN_UPDATE_PIN_DIC_PRODUTOS_PERC_DILUICAO]
	@ID int
AS
BEGIN

	DECLARE @ID_RECEITA int,@VERSAO int ;

	-- variáveis do bloco ATUALIZA CONSUMOS (declaradas fora do ciclo, limpas em cada iteração)
	DECLARE @TAXA_REJEICAO decimal(19,2);
	DECLARE @sumTipoAcabamento_A TABLE (ID_TIPO_ACABAMENTO int,ID_REFERENCIA_A int,TOTAL decimal(19,2))
	DECLARE @sumTipoAcabamento_C TABLE (ID_TIPO_ACABAMENTO int,ID_REFERENCIA_C int,TOTAL decimal(19,2))
	DECLARE @sumTipoAcabamento2_C TABLE (ID_TIPO_ACABAMENTO int,ID_REFERENCIA2_C int,TOTAL decimal(19,2))
	DECLARE @sumTipoAcabamento3_C TABLE (ID_TIPO_ACABAMENTO int,ID_REFERENCIA3_C int,TOTAL decimal(19,2))
	DECLARE @sumTipoAcabamento4_C TABLE (ID_TIPO_ACABAMENTO int,ID_REFERENCIA4_C int,TOTAL decimal(19,2))
	DECLARE @sumTipoAcabamento5_C TABLE (ID_TIPO_ACABAMENTO int,ID_REFERENCIA5_C int,TOTAL decimal(19,2))
	DECLARE @sumTipoAcabamento TABLE (ID_TIPO_ACABAMENTO int,TOTAL decimal(19,2))

	DECLARE receita_cursor CURSOR FOR
	select distinct c.ID ,C.VERSAO
	from ( 	select a.COD_REF as REFERENCIA_C,b.COD_REF as REFERENCIA_A from PIN_DIC_PRODUTOS_RELACIONADOS a
	inner join  PIN_DIC_PRODUTOS b on  a.ID_PRODUTO = b.ID
	where a.ID_PRODUTO = @ID ) p
	inner join PIN_MOV_RECEITAS_LINHAS a on a.REFERENCIA_C  = p.REFERENCIA_C and a.REFERENCIA_A = p.REFERENCIA_A
	inner join PIN_MOV_RECEITAS c on a.ID_RECEITA = c.ID and a.VERSAO = c.VERSAO
	where   c.VERSAO_ATIVA = 1  and c.INATIVO = 0 and ISNULL(c.RECEITA_INATIVA,0) = 0

	OPEN receita_cursor

	FETCH NEXT FROM receita_cursor INTO @ID_RECEITA,@VERSAO

	WHILE @@FETCH_STATUS = 0
	BEGIN

		UPDATE PIN_MOV_RECEITAS SET INATIVO = 1 , VERSAO_ATIVA = 0 WHERE ID= @ID_RECEITA  and VERSAO = @VERSAO
		INSERT INTO [dbo].[PIN_MOV_RECEITAS]([ID],[VERSAO] ,[DATA_CRIA],[UTZ_CRIA],[DATA_MODIF],[UTZ_MODIF],[DATA_ANULA],[UTZ_ANULA],[INATIVO],[NOME_PROJETO],[MASTER],[LIMPEZA_IPA],[CO2],[CURA],[JOB],[COR],[LINHA],[COD_FORNECEDOR],[NOME_FORNECEDOR],[OBSERVACOES],[FLAMEADO],[REFERENCIA_PINTURA],[NOME_REFERENCIA_PINTURA],[ASPETO],[ACABAMENTOS],[PRIMARIO],[BASE],[VERNIZ],[CARTELA],[RACK],[NOME_COR],[COD_ASPETO],[QUANTIDADES_RACK],[PECAS_RACK],[VERSAO_ATIVA],[ID_COR],RECEITA_INATIVA,TAXA_REJEICAO,TEMPERATURA_MAX,TEMPERATURA_MIN,TEMPO_FLASHOFF,CICLO_PRIMARIO,CICLO_BASE,CICLO_VERNIZ,CLASSIFICACAO)

		SELECT [ID],@VERSAO +1 ,GETDATE() as DATA_CRIA,[UTZ_CRIA],GETDATE() as [DATA_MODIF],[UTZ_MODIF],[DATA_ANULA],[UTZ_ANULA],0 [INATIVO],[NOME_PROJETO],[MASTER],[LIMPEZA_IPA],[CO2],[CURA],[JOB],[COR],[LINHA],[COD_FORNECEDOR],[NOME_FORNECEDOR],[OBSERVACOES],[FLAMEADO],[REFERENCIA_PINTURA],[NOME_REFERENCIA_PINTURA],[ASPETO],[ACABAMENTOS],[PRIMARIO],[BASE],[VERNIZ],[CARTELA],[RACK],[NOME_COR],[COD_ASPETO],[QUANTIDADES_RACK],[PECAS_RACK],1 [VERSAO_ATIVA],[ID_COR],0,TAXA_REJEICAO
		,TEMPERATURA_MAX,TEMPERATURA_MIN,TEMPO_FLASHOFF,CICLO_PRIMARIO,CICLO_BASE,CICLO_VERNIZ,CLASSIFICACAO
		FROM PIN_MOV_RECEITAS where ID= @ID_RECEITA  and VERSAO = @VERSAO

		INSERT INTO [dbo].[PIN_MOV_RECEITAS_LINHAS]([ID_RECEITA],[VERSAO],[ID_TIPO_ACABAMENTO],[UNIDADE],[ID_POTE],[ID_POTE_CATALISADOR],[REFERENCIA_A],[REFERENCIA_B],
		[REFERENCIA_C],
		[REFERENCIA2_C],
		[REFERENCIA3_C],
		[REFERENCIA4_C],
		[REFERENCIA5_C],
		[VALVULA_POTE],[VALVULA_CATALISADOR],[COR_A],
		[DILUENTE_C],
		[DILUENTE2_C],
		[DILUENTE3_C],
		[DILUENTE4_C],
		[DILUENTE5_C],
		[ADITIVO],[TAXA_MISTURA],[PADRAO_VISCOSIDADE],[POT_LIFE],[ARMAZEM_A],[ARMAZEM_B],[ARMAZEM_C],[ARMAZEM_ADITIVO],[CODIGO_COR],[ID_REFERENCIA_A],[ID_REFERENCIA_B],
		[ID_REFERENCIA_C],
		[ID_REFERENCIA2_C],
		[ID_REFERENCIA3_C],
		[ID_REFERENCIA4_C],
		[ID_REFERENCIA5_C],
		[ESPESSURA],[BRILHO],[ID_PRE_SET],[CAUDAL],[PRESSAO_AUTOMATICA],[PRESSAO_LEQUE],[VELOCIDADE],[TAMANHO_BICO],[VOLTAS_PISTOLA],CONSUMO_RACK_COR,CONSUMO_RACK_DILUENTE,QTD_RACK_REFERENCIA_A,QTD_RACK_REFERENCIA_B,
		QTD_RACK_REFERENCIA_C,
		QTD_RACK_REFERENCIA2_C,
		QTD_RACK_REFERENCIA3_C,
		QTD_RACK_REFERENCIA4_C,
		QTD_RACK_REFERENCIA5_C,
		NECESSIDADES_RACK_REFERENCIA_A,NECESSIDADES_RACK_REFERENCIA_B,
		NECESSIDADES_RACK_REFERENCIA_C,
		NECESSIDADES_RACK_REFERENCIA2_C,
		NECESSIDADES_RACK_REFERENCIA3_C,
		NECESSIDADES_RACK_REFERENCIA4_C,
		NECESSIDADES_RACK_REFERENCIA5_C,
		PRESSAO_ENTRADA
		,PRESSAO_RETORNO
		,TEMPERATURA
		,CONSUMO_CARGA_COR
		,CONSUMO_CARGA_CATALISADOR
		)
		SELECT [ID_RECEITA],@VERSAO + 1 [VERSAO],a.[ID_TIPO_ACABAMENTO],[UNIDADE],[ID_POTE],[ID_POTE_CATALISADOR],[REFERENCIA_A],[REFERENCIA_B],
		[REFERENCIA_C],
		[REFERENCIA2_C],
		[REFERENCIA3_C],
		[REFERENCIA4_C],
		[REFERENCIA5_C],
		[VALVULA_POTE],[VALVULA_CATALISADOR],[COR_A],
		CASE WHEN b.PERC_DILUICAO is null THEN  [DILUENTE_C] ELSE  b.PERC_DILUICAO END [DILUENTE_C],
		CASE WHEN b2.PERC_DILUICAO is null THEN  [DILUENTE2_C] ELSE  b2.PERC_DILUICAO END [DILUENTE2_C],
		CASE WHEN b3.PERC_DILUICAO is null THEN  [DILUENTE3_C] ELSE  b3.PERC_DILUICAO END [DILUENTE3_C],
		CASE WHEN b4.PERC_DILUICAO is null THEN  [DILUENTE4_C] ELSE  b4.PERC_DILUICAO END [DILUENTE4_C],
		CASE WHEN b5.PERC_DILUICAO is null THEN  [DILUENTE5_C] ELSE  b5.PERC_DILUICAO END [DILUENTE5_C],
		[ADITIVO],
		CASE WHEN b.PERC_DILUICAO is null THEN   [TAXA_MISTURA] ELSE 	dbo.[atualizardadosTaxaMisturaRobot](a.ID) END  [TAXA_MISTURA],
		[PADRAO_VISCOSIDADE],[POT_LIFE],[ARMAZEM_A],[ARMAZEM_B],[ARMAZEM_C],[ARMAZEM_ADITIVO],[CODIGO_COR],[ID_REFERENCIA_A],[ID_REFERENCIA_B],
		[ID_REFERENCIA_C],
		[ID_REFERENCIA2_C],
		[ID_REFERENCIA3_C],
		[ID_REFERENCIA4_C],
		[ID_REFERENCIA5_C],
		[ESPESSURA],[BRILHO],[ID_PRE_SET],
		a.[CAUDAL] as [CAUDAL],
		a.[PRESSAO_AUTOMATICA] as [PRESSAO_AUTOMATICA],
		a.[PRESSAO_LEQUE] as [PRESSAO_LEQUE],
		a.[VELOCIDADE] as [VELOCIDADE],
		a.[TAMANHO_BICO] as [TAMANHO_BICO],
		a.[VOLTAS_PISTOLA] as [VOLTAS_PISTOLA]
		,CONSUMO_RACK_COR,CONSUMO_RACK_DILUENTE,QTD_RACK_REFERENCIA_A,QTD_RACK_REFERENCIA_B
		,QTD_RACK_REFERENCIA_C
		,QTD_RACK_REFERENCIA2_C
		,QTD_RACK_REFERENCIA3_C
		,QTD_RACK_REFERENCIA4_C
		,QTD_RACK_REFERENCIA5_C
		,NECESSIDADES_RACK_REFERENCIA_A,NECESSIDADES_RACK_REFERENCIA_B
		,NECESSIDADES_RACK_REFERENCIA_C
		,NECESSIDADES_RACK_REFERENCIA2_C
		,NECESSIDADES_RACK_REFERENCIA3_C
		,NECESSIDADES_RACK_REFERENCIA4_C
		,NECESSIDADES_RACK_REFERENCIA5_C
		,a.PRESSAO_ENTRADA
		,a.PRESSAO_RETORNO
		,a.TEMPERATURA
		,a.CONSUMO_CARGA_COR
		,a.CONSUMO_CARGA_CATALISADOR
		FROM PIN_MOV_RECEITAS_LINHAS  a
		LEFT JOIN (
			select * from (
				select  xb.PERC_DILUICAO,xa.ID,ROW_NUMBER() OVER(PARTITION BY xa.ID order by xa.ID) rn from PIN_MOV_RECEITAS_LINHAS xa
				inner join  PIN_DIC_PRODUTOS_RELACIONADOS xb on  xa.REFERENCIA_C = xb.COD_REF
				inner join  PIN_DIC_PRODUTOS xc on  xa.REFERENCIA_A = xc.COD_REF and xb.ID_PRODUTO = xc.ID
				where  xc.INATIVO = 0 and xb.ID_PRODUTO = @ID
			) g where rn = 1
		) b on a.ID = b.ID
		LEFT JOIN (
			select * from (
				select  xb.PERC_DILUICAO,xa.ID,ROW_NUMBER() OVER(PARTITION BY xa.ID order by xa.ID) rn from PIN_MOV_RECEITAS_LINHAS xa
				inner join  PIN_DIC_PRODUTOS_RELACIONADOS xb on  xa.REFERENCIA2_C = xb.COD_REF
				inner join  PIN_DIC_PRODUTOS xc on  xa.REFERENCIA_A = xc.COD_REF and xb.ID_PRODUTO = xc.ID
				where  xc.INATIVO = 0 and xb.ID_PRODUTO = @ID
			) g where rn = 1
		) b2 on a.ID = b2.ID
		LEFT JOIN (
			select * from (
				select  xb.PERC_DILUICAO,xa.ID,ROW_NUMBER() OVER(PARTITION BY xa.ID order by xa.ID) rn from PIN_MOV_RECEITAS_LINHAS xa
				inner join  PIN_DIC_PRODUTOS_RELACIONADOS xb on  xa.REFERENCIA3_C = xb.COD_REF
				inner join  PIN_DIC_PRODUTOS xc on  xa.REFERENCIA_A = xc.COD_REF and xb.ID_PRODUTO = xc.ID
				where  xc.INATIVO = 0 and xb.ID_PRODUTO = @ID
			) g where rn = 1
		) b3 on a.ID = b3.ID
		LEFT JOIN (
			select * from (
				select  xb.PERC_DILUICAO,xa.ID,ROW_NUMBER() OVER(PARTITION BY xa.ID order by xa.ID) rn from PIN_MOV_RECEITAS_LINHAS xa
				inner join  PIN_DIC_PRODUTOS_RELACIONADOS xb on  xa.REFERENCIA4_C = xb.COD_REF
				inner join  PIN_DIC_PRODUTOS xc on  xa.REFERENCIA_A = xc.COD_REF and xb.ID_PRODUTO = xc.ID
				where  xc.INATIVO = 0 and xb.ID_PRODUTO = @ID
			) g where rn = 1
		) b4 on a.ID = b4.ID
		LEFT JOIN (
			select * from (
				select  xb.PERC_DILUICAO,xa.ID,ROW_NUMBER() OVER(PARTITION BY xa.ID order by xa.ID) rn from PIN_MOV_RECEITAS_LINHAS xa
				inner join  PIN_DIC_PRODUTOS_RELACIONADOS xb on  xa.REFERENCIA5_C = xb.COD_REF
				inner join  PIN_DIC_PRODUTOS xc on  xa.REFERENCIA_A = xc.COD_REF and xb.ID_PRODUTO = xc.ID
				where  xc.INATIVO = 0 and xb.ID_PRODUTO = @ID
			) g where rn = 1
		) b5 on a.ID = b5.ID
		where ID_RECEITA= @ID_RECEITA  and VERSAO = @VERSAO
		order by a.ID

		INSERT INTO PIN_MOV_RECEITAS_REFERENCIAS(VERSAO,ID_RECEITA,DATA_CRIA,UTZ_CRIA,DATA_MODIF,UTZ_MODIF,REFERENCIA_PINTURA,NOME_REFERENCIA_PINTURA,RACK,QUANTIDADES_RACK,PECAS_RACK,TAXA_REJEICAO)
		SELECT @VERSAO + 1  VERSAO,ID_RECEITA,GETDATE() as DATA_CRIA,UTZ_CRIA,GETDATE() as DATA_MODIF,UTZ_MODIF,REFERENCIA_PINTURA,NOME_REFERENCIA_PINTURA,RACK,QUANTIDADES_RACK,PECAS_RACK,TAXA_REJEICAO
		FROM PIN_MOV_RECEITAS_REFERENCIAS a
		WHERE ID_RECEITA= @ID_RECEITA  and VERSAO = @VERSAO
		order by a.ID

		-- copiar a tabela de UV radiation para a nova versão
		INSERT INTO PIN_MOV_UV_RADIATION(VERSAO,ID_RECEITA,DATA_CRIA,UTZ_CRIA,DATA_MODIF,UTZ_MODIF,UV_RADIATION,RECOMMENDED_VALUE)
		SELECT @VERSAO + 1  VERSAO,ID_RECEITA,GETDATE() as DATA_CRIA,UTZ_CRIA,GETDATE() as DATA_MODIF,UTZ_MODIF,UV_RADIATION,RECOMMENDED_VALUE
		FROM PIN_MOV_UV_RADIATION a
		WHERE ID_RECEITA= @ID_RECEITA  and VERSAO = @VERSAO
		order by a.ID

		--ATUALIZA CONSUMOS (dentro do ciclo: corre para todas as receitas processadas)
		DELETE FROM @sumTipoAcabamento_A;
		DELETE FROM @sumTipoAcabamento_C;
		DELETE FROM @sumTipoAcabamento2_C;
		DELETE FROM @sumTipoAcabamento3_C;
		DELETE FROM @sumTipoAcabamento4_C;
		DELETE FROM @sumTipoAcabamento5_C;
		DELETE FROM @sumTipoAcabamento;

		SET @TAXA_REJEICAO = (select TAXA_REJEICAO from PIN_MOV_RECEITAS where ID = @ID_RECEITA and VERSAO = @VERSAO+1)

		INSERT INTO @sumTipoAcabamento_A select ID_TIPO_ACABAMENTO,ID_REFERENCIA_A,SUM(ISNULL(CAST(DILUENTE_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE2_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE3_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE4_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE5_C as decimal(19,2)),0)) TOTAL  from  PIN_MOV_RECEITAS_LINHAS  where ID_RECEITA = @ID_RECEITA and VERSAO = @VERSAO+1 GROUP BY ID_TIPO_ACABAMENTO,ID_REFERENCIA_A
		INSERT INTO @sumTipoAcabamento_C select ID_TIPO_ACABAMENTO,ID_REFERENCIA_C,SUM(ISNULL(CAST(DILUENTE_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE2_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE3_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE4_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE5_C as decimal(19,2)),0)) TOTAL  from  PIN_MOV_RECEITAS_LINHAS  where ID_RECEITA = @ID_RECEITA and VERSAO = @VERSAO+1 GROUP BY ID_TIPO_ACABAMENTO,ID_REFERENCIA_C

		INSERT INTO @sumTipoAcabamento2_C select ID_TIPO_ACABAMENTO,ID_REFERENCIA2_C,SUM(ISNULL(CAST(DILUENTE2_C as decimal(19,2)),0)) TOTAL  from  PIN_MOV_RECEITAS_LINHAS  where ID_RECEITA = @ID_RECEITA and VERSAO = @VERSAO+1 GROUP BY ID_TIPO_ACABAMENTO,ID_REFERENCIA2_C
		INSERT INTO @sumTipoAcabamento3_C select ID_TIPO_ACABAMENTO,ID_REFERENCIA3_C,SUM(ISNULL(CAST(DILUENTE3_C as decimal(19,2)),0)) TOTAL  from  PIN_MOV_RECEITAS_LINHAS  where ID_RECEITA = @ID_RECEITA and VERSAO = @VERSAO+1 GROUP BY ID_TIPO_ACABAMENTO,ID_REFERENCIA3_C
		INSERT INTO @sumTipoAcabamento4_C select ID_TIPO_ACABAMENTO,ID_REFERENCIA4_C,SUM(ISNULL(CAST(DILUENTE4_C as decimal(19,2)),0)) TOTAL  from  PIN_MOV_RECEITAS_LINHAS  where ID_RECEITA = @ID_RECEITA and VERSAO = @VERSAO+1 GROUP BY ID_TIPO_ACABAMENTO,ID_REFERENCIA4_C
		INSERT INTO @sumTipoAcabamento5_C select ID_TIPO_ACABAMENTO,ID_REFERENCIA5_C,SUM(ISNULL(CAST(DILUENTE5_C as decimal(19,2)),0)) TOTAL  from  PIN_MOV_RECEITAS_LINHAS  where ID_RECEITA = @ID_RECEITA and VERSAO = @VERSAO+1 GROUP BY ID_TIPO_ACABAMENTO,ID_REFERENCIA5_C

		INSERT INTO @sumTipoAcabamento select ID_TIPO_ACABAMENTO,SUM(ISNULL(CAST(DILUENTE_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE2_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE3_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE4_C as decimal(19,2)),0)+ISNULL(CAST(DILUENTE5_C as decimal(19,2)),0)) TOTAL  from  PIN_MOV_RECEITAS_LINHAS  where ID_RECEITA = @ID_RECEITA and VERSAO = @VERSAO+1 GROUP BY ID_TIPO_ACABAMENTO

		if  @TAXA_REJEICAO is null or @TAXA_REJEICAO = 0 begin
			set @TAXA_REJEICAO = 0;
		end else begin
			set @TAXA_REJEICAO = (@TAXA_REJEICAO / 100) + 1;
		end

		UPDATE a SET
		a.CONSUMO_RACK_DILUENTE = b.CONSUMO_RACK_DILUENTE,
		a.QTD_RACK_REFERENCIA_A = b.QTD_RACK_REFERENCIA_A,
		a.QTD_RACK_REFERENCIA_B = b.QTD_RACK_REFERENCIA_B,
		a.QTD_RACK_REFERENCIA_C = b.QTD_RACK_REFERENCIA_C,
		a.QTD_RACK_REFERENCIA2_C = b.QTD_RACK_REFERENCIA2_C,
		a.QTD_RACK_REFERENCIA3_C = b.QTD_RACK_REFERENCIA3_C,
		a.QTD_RACK_REFERENCIA4_C = b.QTD_RACK_REFERENCIA4_C,
		a.QTD_RACK_REFERENCIA5_C = b.QTD_RACK_REFERENCIA5_C,
		a.NECESSIDADES_RACK_REFERENCIA_A = b.NECESSIDADES_RACK_REFERENCIA_A,
		a.NECESSIDADES_RACK_REFERENCIA_B = b.NECESSIDADES_RACK_REFERENCIA_B,
		a.NECESSIDADES_RACK_REFERENCIA_C = b.NECESSIDADES_RACK_REFERENCIA_C,
		a.NECESSIDADES_RACK_REFERENCIA2_C = b.NECESSIDADES_RACK_REFERENCIA2_C,
		a.NECESSIDADES_RACK_REFERENCIA3_C = b.NECESSIDADES_RACK_REFERENCIA3_C,
		a.NECESSIDADES_RACK_REFERENCIA4_C = b.NECESSIDADES_RACK_REFERENCIA4_C,
		a.NECESSIDADES_RACK_REFERENCIA5_C = b.NECESSIDADES_RACK_REFERENCIA5_C
		 from PIN_MOV_RECEITAS_LINHAS a
		inner join (
		select
		CONSUMO_RACK_DILUENTE
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA_A,0 )) as QTD_RACK_REFERENCIA_A
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA_B,0 )) as QTD_RACK_REFERENCIA_B
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA_C,0 )) as QTD_RACK_REFERENCIA_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA2_C,0 )) as QTD_RACK_REFERENCIA2_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA3_C,0 )) as QTD_RACK_REFERENCIA3_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA4_C,0 )) as QTD_RACK_REFERENCIA4_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA5_C,0 )) as QTD_RACK_REFERENCIA5_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA_A,0 )* @TAXA_REJEICAO)  as NECESSIDADES_RACK_REFERENCIA_A
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA_B,0 )* @TAXA_REJEICAO)  as NECESSIDADES_RACK_REFERENCIA_B
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA_C,0 )* @TAXA_REJEICAO)  as NECESSIDADES_RACK_REFERENCIA_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA2_C,0 )* @TAXA_REJEICAO)  as NECESSIDADES_RACK_REFERENCIA2_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA3_C,0 )* @TAXA_REJEICAO)  as NECESSIDADES_RACK_REFERENCIA3_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA4_C,0 )* @TAXA_REJEICAO)  as NECESSIDADES_RACK_REFERENCIA4_C
		,TRY_CONVERT(decimal(19,4),ISNULL(QTD_RACK_REFERENCIA5_C,0 )* @TAXA_REJEICAO)  as NECESSIDADES_RACK_REFERENCIA5_C
		,ID
		from (
			select
				CONSUMO_RACK_DILUENTE
				,case when ID_REFERENCIA_A is null or ROW_NUMBER()OVER(PARTITION BY ID_REFERENCIA_A ,ID_TIPO_ACABAMENTO ORDER BY  case when NOME like '%primário%' then 1 when NOME like '%base%' then 2 when NOME like '%verniz%' then 3 else 4 end ) > 1 then null else TRY_CONVERT(decimal(19,4), ((CONSUMO_RACK_COR * COR_A) / (COR_A + (select SUM(x.TOTAL) from @sumTipoAcabamento_A x where x.ID_REFERENCIA_A = a.ID_REFERENCIA_A and x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO) ))/1000 ) end QTD_RACK_REFERENCIA_A
				,case when ID_REFERENCIA_B is null or ROW_NUMBER()OVER(PARTITION BY ID_REFERENCIA_B ,ID_TIPO_ACABAMENTO ORDER BY  case when NOME like '%primário%' then 1 when NOME like '%base%' then 2 when NOME like '%verniz%' then 3 else 4 end ) > 1 then null else TRY_CONVERT(decimal(19,4), (CONSUMO_RACK_DILUENTE)/1000 ) end QTD_RACK_REFERENCIA_B
				,case when ID_REFERENCIA_C is null or ROW_NUMBER()OVER(PARTITION BY ID_REFERENCIA_C ,ID_TIPO_ACABAMENTO ORDER BY  case when NOME like '%primário%' then 1 when NOME like '%base%' then 2 when NOME like '%verniz%' then 3 else 4 end ) > 1 then null else TRY_CONVERT(decimal(19,4), ((CONSUMO_RACK_COR * (select SUM(x.TOTAL) from @sumTipoAcabamento_C x where x.ID_REFERENCIA_C = a.ID_REFERENCIA_C and x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO)) / (COR_A + (select SUM(x.TOTAL) from @sumTipoAcabamento x where  x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO) ))/1000 ) end QTD_RACK_REFERENCIA_C
				,case when ID_REFERENCIA2_C is null or ROW_NUMBER()OVER(PARTITION BY ID_REFERENCIA2_C ,ID_TIPO_ACABAMENTO ORDER BY  case when NOME like '%primário%' then 1 when NOME like '%base%' then 2 when NOME like '%verniz%' then 3 else 4 end ) > 1 then null else TRY_CONVERT(decimal(19,4), ((CONSUMO_RACK_COR * (select SUM(x.TOTAL) from @sumTipoAcabamento2_C x where x.ID_REFERENCIA2_C = a.ID_REFERENCIA2_C and x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO)) / (COR_A + (select SUM(x.TOTAL) from @sumTipoAcabamento x where  x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO) ))/1000 ) end QTD_RACK_REFERENCIA2_C
				,case when ID_REFERENCIA3_C is null or ROW_NUMBER()OVER(PARTITION BY ID_REFERENCIA3_C ,ID_TIPO_ACABAMENTO ORDER BY  case when NOME like '%primário%' then 1 when NOME like '%base%' then 2 when NOME like '%verniz%' then 3 else 4 end ) > 1 then null else TRY_CONVERT(decimal(19,4), ((CONSUMO_RACK_COR * (select SUM(x.TOTAL) from @sumTipoAcabamento3_C x where x.ID_REFERENCIA3_C = a.ID_REFERENCIA3_C and x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO)) / (COR_A + (select SUM(x.TOTAL) from @sumTipoAcabamento x where  x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO) ))/1000 ) end QTD_RACK_REFERENCIA3_C
				,case when ID_REFERENCIA4_C is null or ROW_NUMBER()OVER(PARTITION BY ID_REFERENCIA4_C ,ID_TIPO_ACABAMENTO ORDER BY  case when NOME like '%primário%' then 1 when NOME like '%base%' then 2 when NOME like '%verniz%' then 3 else 4 end ) > 1 then null else TRY_CONVERT(decimal(19,4), ((CONSUMO_RACK_COR * (select SUM(x.TOTAL) from @sumTipoAcabamento4_C x where x.ID_REFERENCIA4_C = a.ID_REFERENCIA4_C and x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO)) / (COR_A + (select SUM(x.TOTAL) from @sumTipoAcabamento x where  x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO) ))/1000 ) end QTD_RACK_REFERENCIA4_C
				,case when ID_REFERENCIA5_C is null or ROW_NUMBER()OVER(PARTITION BY ID_REFERENCIA5_C ,ID_TIPO_ACABAMENTO ORDER BY  case when NOME like '%primário%' then 1 when NOME like '%base%' then 2 when NOME like '%verniz%' then 3 else 4 end ) > 1 then null else TRY_CONVERT(decimal(19,4), ((CONSUMO_RACK_COR * (select SUM(x.TOTAL) from @sumTipoAcabamento5_C x where x.ID_REFERENCIA5_C = a.ID_REFERENCIA5_C and x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO)) / (COR_A + (select SUM(x.TOTAL) from @sumTipoAcabamento x where  x.ID_TIPO_ACABAMENTO = a.ID_TIPO_ACABAMENTO) ))/1000 ) end QTD_RACK_REFERENCIA5_C
				,ID
				from  (
				select
				TRY_CONVERT(decimal(19,1),CONSUMO_RACK_COR / NULLIF(CASE WHEN TAXA_MISTURA is null or TAXA_MISTURA = '' then 0 else   CAST(LEFT(REPLACE(TAXA_MISTURA,',','.'), CHARINDEX(':', TAXA_MISTURA) -1 ) as decimal(19,2)) end,0)) CONSUMO_RACK_DILUENTE
				,ID_REFERENCIA_A
				,ID_REFERENCIA_B
				,ID_REFERENCIA_C
				,ID_REFERENCIA2_C
				,ID_REFERENCIA3_C
				,ID_REFERENCIA4_C
				,ID_REFERENCIA5_C
				,CONSUMO_RACK_COR,COR_A,ID_TIPO_ACABAMENTO,a.ID,NOME
				from PIN_MOV_RECEITAS_LINHAS a
				LEFT JOIN PIN_DIC_TIPO_ACABAMENTO x on a.ID_TIPO_ACABAMENTO = x.ID
				where  ID_RECEITA = @ID_RECEITA and VERSAO = @VERSAO+1
			)a
		) a ) b on a.ID = b.ID

		FETCH NEXT FROM receita_cursor
	INTO @ID_RECEITA,@VERSAO
	END
	CLOSE receita_cursor;
	DEALLOCATE receita_cursor;

END
GO
