/* =====================================================================
   Derrogações - Meios de Controlo: Plano de Ações ligado ao sistema
   de Tarefas (GT_MOV_TAREFAS), sub-módulo 'DMC'.
   Espelha QUA_DERROGACOES_PLANOS_ACCOES (sub-módulo 'D').
   ===================================================================== */

-- ---------------------------------------------------------------------
-- 0) Normalizar estados para a convenção do projeto (inicial de 1 letra).
--    Registos antigos podiam ter "Aberta" (>5 chars) e causavam truncação
--    ao materializar a tarefa.
-- ---------------------------------------------------------------------
UPDATE QUA_MC_DERROGACOES   SET ESTADO = 'P' WHERE ESTADO = 'Aberta';
UPDATE QUA_MC_DECLARACOES_NC SET ESTADO = 'P' WHERE ESTADO = 'Aberta';
GO

-- ---------------------------------------------------------------------
-- 1) Alinhar o esquema de QUA_MC_DERROGACOES_ACOES com o plano de ações
--    rico (igual a QUA_DERROGACOES_PLANOS_ACCOES).
-- ---------------------------------------------------------------------
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'ID_ACCAO') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD ID_ACCAO INT;            -- FK GT_DIC_TAREFAS(id)
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'TIPO_RESPONSAVEL') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD TIPO_RESPONSAVEL NVARCHAR(5);  -- 'u' utilizador | 'g' grupo
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'DATA_PREVISTA') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD DATA_PREVISTA DATE;
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'DATA_REAL') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD DATA_REAL DATE;
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'OBSERVACOES') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD OBSERVACOES NVARCHAR(MAX);
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'AREA') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD AREA NVARCHAR(255);
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'OBRIGA_EVIDENCIAS') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD OBRIGA_EVIDENCIAS BIT;
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'CONCLUIDO_UTZ') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD CONCLUIDO_UTZ INT;
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'CONCLUIDO_DATA') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD CONCLUIDO_DATA DATE;
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'TIPO') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD TIPO NVARCHAR(5);        -- 'A' = ação do plano
GO
IF COL_LENGTH('QUA_MC_DERROGACOES_ACOES', 'ORDEM') IS NULL
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ADD ORDEM INT;
GO

-- RESPONSAVEL passa a guardar o ID do utilizador (INT). Limpar valores
-- não-numéricos antigos antes de converter (dev: tabela praticamente vazia).
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'QUA_MC_DERROGACOES_ACOES' AND COLUMN_NAME = 'RESPONSAVEL'
             AND DATA_TYPE IN ('nvarchar','varchar','char','nchar'))
BEGIN
    UPDATE QUA_MC_DERROGACOES_ACOES SET RESPONSAVEL = NULL WHERE TRY_CONVERT(INT, RESPONSAVEL) IS NULL;
    ALTER TABLE QUA_MC_DERROGACOES_ACOES ALTER COLUMN RESPONSAVEL INT;
END
GO


-- ---------------------------------------------------------------------
-- 2) Stored procedure GT_MOV_TAREFAS_INSERT_UPDATE: ramo 'DMC'
--    (lê de QUA_MC_DERROGACOES_ACOES, à semelhança de 'D').
-- ---------------------------------------------------------------------
GO
ALTER PROCEDURE [dbo].[GT_MOV_TAREFAS_INSERT_UPDATE]
	@ID_CAMPO int,
	@ID_MODULO int,
	@SUB_MODULO varchar(5)
AS
BEGIN
	SET NOCOUNT ON;

declare @id int = 0;
declare @id_insert int = 0;
declare @SUB_MODULO_CODE varchar(5);

IF   @SUB_MODULO is null BEGIN
		SET @SUB_MODULO_CODE = (select top 1 c.TIPO_RECLAMACAO from RC_MOV_RECLAMACAO c inner join  RC_MOV_RECLAMACAO_PLANOS_ACCOES  b on c.ID_RECLAMACAO = b.ID_RECLAMACAO where b.ID = @ID_CAMPO);
	END
	ELSE IF @SUB_MODULO = 'D' BEGIN
		SET @SUB_MODULO_CODE = 'D';
	END
	ELSE IF @SUB_MODULO = 'DMC' BEGIN
		SET @SUB_MODULO_CODE = 'DMC';
	END
	ELSE IF @SUB_MODULO = 'F' BEGIN
		SET @SUB_MODULO_CODE = 'F';
	END
	ELSE IF @SUB_MODULO = 'R' BEGIN
		SET @SUB_MODULO_CODE = 'R';
	END
	ELSE IF @SUB_MODULO = 'SUG' BEGIN
		SET @SUB_MODULO_CODE = 'SUG';
	END

IF EXISTS (SELECT * FROM GT_MOV_TAREFAS a WHERE ID_MODULO = @ID_MODULO and  ID_CAMPO= @ID_CAMPO AND SUB_MODULO = @SUB_MODULO_CODE)  AND  @SUB_MODULO is null BEGIN

	UPDATE a  SET @id = a.ID_TAREFA, a.DATA_FIM = b.DATA_PREVISTA,a.DATA_INICIO = b.DATA_CRIA, a.DATA_ULT_MODIF = a.DATA_ULT_MODIF,a.UTZ_ULT_MODIF = a.UTZ_ULT_MODIF
	,a.OBSERVACOES=b.OBSERVACOES, a.UTZ_ID = b.RESPONSAVEL, a.UTZ_TIPO = b.TIPO_RESPONSAVEL,a.ID_ACCAO = b.ID_ACCAO
	, a.SUB_MODULO =  (select c.TIPO_RECLAMACAO from RC_MOV_RECLAMACAO c where c.ID_RECLAMACAO = b.ID_RECLAMACAO)
	, a.PRIORIDADE =  (select c.GRAU_IMPORTANCIA from RC_MOV_RECLAMACAO c where c.ID_RECLAMACAO = b.ID_RECLAMACAO)
	FROM GT_MOV_TAREFAS a inner join RC_MOV_RECLAMACAO_PLANOS_ACCOES b on a.ID_CAMPO = b.ID
	where a.ID_CAMPO = @ID_CAMPO and a.ID_MODULO = @ID_MODULO

END
ELSE IF EXISTS (SELECT * FROM GT_MOV_TAREFAS a WHERE ID_MODULO = @ID_MODULO and  ID_CAMPO= @ID_CAMPO AND SUB_MODULO = @SUB_MODULO_CODE) AND  @SUB_MODULO = 'D' BEGIN
	UPDATE a  SET @id = a.ID_TAREFA, a.DATA_FIM = b.DATA_PREVISTA,a.DATA_INICIO = b.DATA_CRIA, a.DATA_ULT_MODIF = a.DATA_ULT_MODIF,a.UTZ_ULT_MODIF = a.UTZ_ULT_MODIF
	,a.OBSERVACOES=b.OBSERVACOES, a.UTZ_ID = b.RESPONSAVEL, a.UTZ_TIPO = b.TIPO_RESPONSAVEL,a.ID_ACCAO = b.ID_ACCAO
	, a.SUB_MODULO =  'D'
	, a.PRIORIDADE =  3
	FROM GT_MOV_TAREFAS a inner join QUA_DERROGACOES_PLANOS_ACCOES b on a.ID_CAMPO = b.ID
	where a.ID_CAMPO = @ID_CAMPO and a.ID_MODULO = @ID_MODULO
END
ELSE IF EXISTS (SELECT * FROM GT_MOV_TAREFAS a WHERE ID_MODULO = @ID_MODULO and  ID_CAMPO= @ID_CAMPO AND SUB_MODULO = @SUB_MODULO_CODE) AND  @SUB_MODULO = 'DMC' BEGIN
	UPDATE a  SET @id = a.ID_TAREFA, a.DATA_FIM = b.DATA_PREVISTA,a.DATA_INICIO = b.DATA_CRIA, a.DATA_ULT_MODIF = a.DATA_ULT_MODIF,a.UTZ_ULT_MODIF = a.UTZ_ULT_MODIF
	,a.OBSERVACOES=b.OBSERVACOES, a.UTZ_ID = b.RESPONSAVEL, a.UTZ_TIPO = b.TIPO_RESPONSAVEL,a.ID_ACCAO = b.ID_ACCAO
	, a.SUB_MODULO =  'DMC'
	, a.PRIORIDADE =  3
	FROM GT_MOV_TAREFAS a inner join QUA_MC_DERROGACOES_ACOES b on a.ID_CAMPO = b.ID
	where a.ID_CAMPO = @ID_CAMPO and a.ID_MODULO = @ID_MODULO
END
ELSE IF EXISTS (SELECT * FROM GT_MOV_TAREFAS a WHERE ID_MODULO = @ID_MODULO and  ID_CAMPO= @ID_CAMPO AND SUB_MODULO = @SUB_MODULO_CODE) AND  @SUB_MODULO = 'F' BEGIN
	UPDATE a  SET @id = a.ID_TAREFA, a.DATA_FIM = b.DATA_PREVISTA,a.DATA_INICIO = b.DATA_CRIA, a.DATA_ULT_MODIF = a.DATA_ULT_MODIF,a.UTZ_ULT_MODIF = a.UTZ_ULT_MODIF
	,a.OBSERVACOES=b.OBSERVACOES, a.UTZ_ID = b.RESPONSAVEL, a.UTZ_TIPO = b.TIPO_RESPONSAVEL,a.ID_ACCAO = b.ID_ACCAO
	, a.SUB_MODULO =  'F'
	, a.PRIORIDADE =  (select c.GRAU_IMPORTANCIA from RC_MOV_RECLAMACAO_FORNECEDOR c where c.ID_RECLAMACAO = b.ID_RECLAMACAO)
	FROM GT_MOV_TAREFAS a inner join RC_MOV_RECLAMACAO_FORNECEDOR_PLANOS_ACCOES b on a.ID_CAMPO = b.ID
	where a.ID_CAMPO = @ID_CAMPO and a.ID_MODULO = @ID_MODULO
END
ELSE IF EXISTS (SELECT * FROM GT_MOV_TAREFAS a WHERE ID_MODULO = @ID_MODULO and  ID_CAMPO= @ID_CAMPO AND SUB_MODULO = @SUB_MODULO_CODE) AND  @SUB_MODULO = 'R' BEGIN
	UPDATE a  SET @id = a.ID_TAREFA, a.DATA_FIM = b.DATA_PREVISTA,a.DATA_INICIO = b.DATA_CRIA, a.DATA_ULT_MODIF = a.DATA_ULT_MODIF,a.UTZ_ULT_MODIF = a.UTZ_ULT_MODIF
	,a.OBSERVACOES=b.OBSERVACOES, a.UTZ_ID = b.RESPONSAVEL, a.UTZ_TIPO = b.TIPO_RESPONSAVEL,a.ID_ACCAO = b.ID_ACCAO
	, a.SUB_MODULO =  'R'
	, a.PRIORIDADE =  3
	FROM GT_MOV_TAREFAS a inner join REU_REUNIOES_PLANOS_ACCOES b on a.ID_CAMPO = b.ID
	where a.ID_CAMPO = @ID_CAMPO and a.ID_MODULO = @ID_MODULO
END
ELSE IF EXISTS (SELECT * FROM GT_MOV_TAREFAS a WHERE ID_MODULO = @ID_MODULO and  ID_CAMPO= @ID_CAMPO AND SUB_MODULO = @SUB_MODULO_CODE) AND  @SUB_MODULO = 'SUG' BEGIN
	UPDATE a  SET @id = a.ID_TAREFA, a.DATA_FIM = b.DATA_PREVISTA,a.DATA_INICIO = b.DATA_CRIA, a.DATA_ULT_MODIF = a.DATA_ULT_MODIF,a.UTZ_ULT_MODIF = a.UTZ_ULT_MODIF
	,a.OBSERVACOES=b.OBSERVACOES, a.UTZ_ID = b.RESPONSAVEL, a.UTZ_TIPO = b.TIPO_RESPONSAVEL,a.ID_ACCAO = b.ID_ACCAO
	, a.SUB_MODULO =  'SUG'
	, a.PRIORIDADE =  3
	FROM GT_MOV_TAREFAS a inner join RH_SUGESTOES_PLANOS_ACCOES b on a.ID_CAMPO = b.ID
	where a.ID_CAMPO = @ID_CAMPO and a.ID_MODULO = @ID_MODULO
END

ELSE BEGIN
	IF   @SUB_MODULO is null BEGIN
		INSERT INTO GT_MOV_TAREFAS(ID_MODULO,ID_CAMPO,DATA_FIM,DATA_INICIO,DATA_CRIA,UTZ_CRIA,DATA_ULT_MODIF,UTZ_ULT_MODIF,ESTADO,INATIVO,UTZ_ID,UTZ_TIPO,ID_ACCAO,SUB_MODULO,PRIORIDADE,OBSERVACOES)
		select @ID_MODULO,ID,DATA_PREVISTA,DATA_CRIA,DATA_CRIA,UTZ_CRIA,DATA_CRIA,UTZ_CRIA,'P',0,RESPONSAVEL,TIPO_RESPONSAVEL,ID_ACCAO,
		(select TIPO_RECLAMACAO from RC_MOV_RECLAMACAO b where b.ID_RECLAMACAO = a.ID_RECLAMACAO),
		(select GRAU_IMPORTANCIA from RC_MOV_RECLAMACAO b where b.ID_RECLAMACAO = a.ID_RECLAMACAO),OBSERVACOES
		from RC_MOV_RECLAMACAO_PLANOS_ACCOES a  where ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'D' BEGIN
		INSERT INTO GT_MOV_TAREFAS(ID_MODULO,ID_CAMPO,DATA_FIM,DATA_INICIO,DATA_CRIA,UTZ_CRIA,DATA_ULT_MODIF,UTZ_ULT_MODIF,ESTADO,INATIVO,UTZ_ID,UTZ_TIPO,ID_ACCAO,SUB_MODULO,PRIORIDADE,OBSERVACOES)
		select @ID_MODULO,ID,DATA_PREVISTA,DATA_CRIA,DATA_CRIA,UTZ_CRIA,DATA_CRIA,UTZ_CRIA,'P',0,RESPONSAVEL,TIPO_RESPONSAVEL,ID_ACCAO,
		'D',
		3,OBSERVACOES
		from QUA_DERROGACOES_PLANOS_ACCOES a  where ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'DMC' BEGIN
		INSERT INTO GT_MOV_TAREFAS(ID_MODULO,ID_CAMPO,DATA_FIM,DATA_INICIO,DATA_CRIA,UTZ_CRIA,DATA_ULT_MODIF,UTZ_ULT_MODIF,ESTADO,INATIVO,UTZ_ID,UTZ_TIPO,ID_ACCAO,SUB_MODULO,PRIORIDADE,OBSERVACOES)
		select @ID_MODULO,ID,DATA_PREVISTA,DATA_CRIA,DATA_CRIA,UTZ_CRIA,DATA_CRIA,UTZ_CRIA,'P',0,RESPONSAVEL,TIPO_RESPONSAVEL,ID_ACCAO,
		'DMC',
		3,OBSERVACOES
		from QUA_MC_DERROGACOES_ACOES a  where ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'F' BEGIN
		INSERT INTO GT_MOV_TAREFAS(ID_MODULO,ID_CAMPO,DATA_FIM,DATA_INICIO,DATA_CRIA,UTZ_CRIA,DATA_ULT_MODIF,UTZ_ULT_MODIF,ESTADO,INATIVO,UTZ_ID,UTZ_TIPO,ID_ACCAO,SUB_MODULO,PRIORIDADE,OBSERVACOES)
		select @ID_MODULO,ID,DATA_PREVISTA,DATA_CRIA,DATA_CRIA,UTZ_CRIA,DATA_CRIA,UTZ_CRIA,'P',0,RESPONSAVEL,TIPO_RESPONSAVEL,ID_ACCAO,
		'F',
		(select GRAU_IMPORTANCIA from RC_MOV_RECLAMACAO_FORNECEDOR b where b.ID_RECLAMACAO = a.ID_RECLAMACAO),OBSERVACOES
		from RC_MOV_RECLAMACAO_FORNECEDOR_PLANOS_ACCOES a  where ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'R' BEGIN
		INSERT INTO GT_MOV_TAREFAS(ID_MODULO,ID_CAMPO,DATA_FIM,DATA_INICIO,DATA_CRIA,UTZ_CRIA,DATA_ULT_MODIF,UTZ_ULT_MODIF,ESTADO,INATIVO,UTZ_ID,UTZ_TIPO,ID_ACCAO,SUB_MODULO,PRIORIDADE,OBSERVACOES)
		select @ID_MODULO,ID,DATA_PREVISTA,DATA_CRIA,DATA_CRIA,UTZ_CRIA,DATA_CRIA,UTZ_CRIA,'P',0,RESPONSAVEL,TIPO_RESPONSAVEL,ID_ACCAO,
		'R',
		3,OBSERVACOES
		from REU_REUNIOES_PLANOS_ACCOES a  where ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'SUG' BEGIN
		INSERT INTO GT_MOV_TAREFAS(ID_MODULO,ID_CAMPO,DATA_FIM,DATA_INICIO,DATA_CRIA,UTZ_CRIA,DATA_ULT_MODIF,UTZ_ULT_MODIF,ESTADO,INATIVO,UTZ_ID,UTZ_TIPO,ID_ACCAO,SUB_MODULO,PRIORIDADE,OBSERVACOES)
		select @ID_MODULO,ID,DATA_PREVISTA,DATA_CRIA,DATA_CRIA,UTZ_CRIA,DATA_CRIA,UTZ_CRIA,'P',0,RESPONSAVEL,TIPO_RESPONSAVEL,ID_ACCAO,
		'SUG' , 3 ,OBSERVACOES
		from RH_SUGESTOES_PLANOS_ACCOES a  where ID  = @ID_CAMPO
	END
END

IF @id != 0 BEGIN
	IF   @SUB_MODULO is null BEGIN
		UPDATE RC_MOV_RECLAMACAO_PLANOS_ACCOES SET ID_TAREFA = @id WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'D' BEGIN
		UPDATE QUA_DERROGACOES_PLANOS_ACCOES SET ID_TAREFA = @id WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'DMC' BEGIN
		UPDATE QUA_MC_DERROGACOES_ACOES SET ID_TAREFA = @id WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'F' BEGIN
		UPDATE RC_MOV_RECLAMACAO_FORNECEDOR_PLANOS_ACCOES SET ID_TAREFA = @id WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'R' BEGIN
		UPDATE REU_REUNIOES_PLANOS_ACCOES SET ID_TAREFA = @id WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'SUG' BEGIN
		UPDATE RH_SUGESTOES_PLANOS_ACCOES SET ID_TAREFA = @id WHERE ID = @ID_CAMPO
	END
END
ELSE BEGIN
	IF   @SUB_MODULO is null BEGIN
		UPDATE RC_MOV_RECLAMACAO_PLANOS_ACCOES SET @id_insert = ID_TAREFA = (SELECT ID_TAREFA FROM GT_MOV_TAREFAS WHERE ID_CAMPO = @ID_CAMPO and ID_MODULO = @ID_MODULO and SUB_MODULO = @SUB_MODULO_CODE)
		WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'D' BEGIN
		UPDATE QUA_DERROGACOES_PLANOS_ACCOES SET @id_insert = ID_TAREFA = (SELECT ID_TAREFA FROM GT_MOV_TAREFAS WHERE ID_CAMPO = @ID_CAMPO and ID_MODULO = @ID_MODULO and SUB_MODULO = @SUB_MODULO_CODE)
		WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'DMC' BEGIN
		UPDATE QUA_MC_DERROGACOES_ACOES SET @id_insert = ID_TAREFA = (SELECT ID_TAREFA FROM GT_MOV_TAREFAS WHERE ID_CAMPO = @ID_CAMPO and ID_MODULO = @ID_MODULO and SUB_MODULO = @SUB_MODULO_CODE)
		WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'F' BEGIN
		UPDATE RC_MOV_RECLAMACAO_FORNECEDOR_PLANOS_ACCOES SET @id_insert = ID_TAREFA = (SELECT ID_TAREFA FROM GT_MOV_TAREFAS WHERE ID_CAMPO = @ID_CAMPO and ID_MODULO = @ID_MODULO and SUB_MODULO = @SUB_MODULO_CODE)
		WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'R' BEGIN
		UPDATE REU_REUNIOES_PLANOS_ACCOES SET @id_insert = ID_TAREFA = (SELECT ID_TAREFA FROM GT_MOV_TAREFAS WHERE ID_CAMPO = @ID_CAMPO and ID_MODULO = @ID_MODULO and SUB_MODULO = @SUB_MODULO_CODE)
		WHERE ID = @ID_CAMPO
	END
	ELSE IF @SUB_MODULO = 'SUG' BEGIN
		UPDATE RH_SUGESTOES_PLANOS_ACCOES SET @id_insert = ID_TAREFA = (SELECT ID_TAREFA FROM GT_MOV_TAREFAS WHERE ID_CAMPO = @ID_CAMPO and ID_MODULO = @ID_MODULO and SUB_MODULO = @SUB_MODULO_CODE)
		WHERE ID = @ID_CAMPO
	END
END


IF @id_insert != 0  BEGIN
	INSERT INTO GT_LOGS ([DATA_CRIA] ,[UTZ_CRIA] ,[DESCRICAO] ,[ID_TAREFA])
	VALUES (GETDATE(),(SELECT UTZ_CRIA FROM GT_MOV_TAREFAS WHERE ID_TAREFA = @id_insert),'Adicionada nova Tarefa',@id_insert)
END

END
GO
